/**
 * Minimal ABI — only the entries this frontend actually consumes, transcribed
 * from the verified Ethereum reference (FWA_ETHEREUM_REFERENCE/FWA/abi.json).
 * The HyperEVM port keeps FWA.sol unchanged (FWA_PARITY_MANIFEST.md §15), so
 * these fragments are expected to remain stable; the deployment manifest stays
 * the only source of addresses.
 */

export const fwaCoreAbi = [
  // ---- pricing / pool state
  {
    type: "function",
    name: "quoteAcquisitionPrice",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "fee", type: "uint256" },
      { name: "vrf", type: "uint256" },
      { name: "total", type: "uint256" },
    ],
  },
  { type: "function", name: "activeListingCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "nextListingId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalWeight", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "weightedBackingTotal",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "activeBackingTotal", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "stagedCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "surchargeBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "minBacking", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "maxAcquisitionsPerTx", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "acquisitionsEnabled", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "withdrawOnly", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  {
    type: "function",
    name: "pendingAcquisitionCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "selectionSlippageBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "topListingId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "topListingPot", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "topListingShareBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "topThresholdBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "listings",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [
      { name: "collection", type: "address" },
      { name: "depositor", type: "address" },
      { name: "purchaser", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "weight", type: "uint256" },
      { name: "value", type: "uint256" },
      { name: "feeShare", type: "uint256" },
      { name: "feeDebt", type: "uint256" },
      { name: "slot", type: "uint256" },
      { name: "allocatedAt", type: "uint64" },
      { name: "status", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "pendingFees",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "lastIssuedSequence", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  {
    type: "function",
    name: "requestIdAtSequence",
    stateMutability: "view",
    inputs: [{ name: "sequence", type: "uint64" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "acquisitions",
    stateMutability: "view",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [
      { name: "purchaser", type: "address" },
      { name: "requestBlock", type: "uint256" },
      { name: "priceEscrowed", type: "uint256" },
      { name: "listingId", type: "uint256" },
      { name: "status", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "acquisitionMeta",
    stateMutability: "view",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [
      { name: "sequence", type: "uint64" },
      { name: "wordDeadlineBlock", type: "uint64" },
      { name: "rewardEpoch", type: "uint64" },
      { name: "maxPositiveSlippageBps", type: "uint16" },
      { name: "maxNegativeSlippageBps", type: "uint16" },
      { name: "randomWord", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "stuckNFTRecipient",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "acquisitionRefundCredit",
    stateMutability: "view",
    inputs: [{ name: "purchaser", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "feeCredit",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "collectionWhitelisted",
    stateMutability: "view",
    inputs: [{ name: "collection", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  { type: "function", name: "settlementWindow", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "finalizeWindow", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "settlementWindowAtAllocation", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint64" }] },
  { type: "function", name: "finalizeWindowAtAllocation", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint64" }] },
  {
    type: "function",
    name: "settlementDiscountBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },

  // ---- writes
  {
    type: "function",
    name: "listNFT",
    stateMutability: "payable",
    inputs: [
      { name: "collection", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [{ name: "listingId", type: "uint256" }],
  },
  {
    type: "function",
    name: "withdrawListing",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acquire",
    stateMutability: "payable",
    inputs: [
      { name: "maxAcquisitionFee", type: "uint256" },
      { name: "minWeightedValue", type: "uint256" },
      { name: "maxNegativeSlippageBps", type: "uint256" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    type: "function",
    name: "acquireBatch",
    stateMutability: "payable",
    inputs: [
      { name: "count", type: "uint256" },
      { name: "maxAcquisitionFee", type: "uint256" },
      { name: "minWeightedValue", type: "uint256" },
      { name: "maxNegativeSlippageBps", type: "uint256" },
    ],
    outputs: [{ name: "requestIds", type: "uint256[]" }],
  },
  { type: "function", name: "keepNFT", stateMutability: "nonpayable", inputs: [{ name: "listingId", type: "uint256" }], outputs: [] },
  {
    type: "function",
    name: "relistNFT",
    stateMutability: "payable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptDepositorBid",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptBidAsTokens",
    stateMutability: "nonpayable",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "minOut", type: "uint256" },
    ],
    outputs: [{ name: "tokenOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "depositorReclaimNFT",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "depositorReclaimBacking",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeUnsettled",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recoverStuckNFT",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  { type: "function", name: "withdrawEarnings", stateMutability: "nonpayable", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "withdrawAcquisitionRefund",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "claimListingFees",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingIds", type: "uint256[]" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "claimTopSpot",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
] as const;

/** Indexed events used for the emergency on-chain account-discovery fallback
 * when the history indexer is unavailable. */
export const fwaAccountDiscoveryAbi = [
  {
    type: "event",
    name: "NFTListed",
    inputs: [
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "slot", type: "uint256" },
      { indexed: true, name: "depositor", type: "address" },
      { indexed: false, name: "collection", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "weight", type: "uint256" },
      { indexed: false, name: "value", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ListingStaged",
    inputs: [
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "depositor", type: "address" },
      { indexed: false, name: "collection", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "value", type: "uint256" },
      { indexed: false, name: "stagedAtBlock", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "NFTAllocated",
    inputs: [
      { indexed: true, name: "requestId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "purchaser", type: "address" },
      { indexed: false, name: "depositor", type: "address" },
      { indexed: false, name: "value", type: "uint256" },
      { indexed: false, name: "randomWord", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "AcquisitionRequested",
    inputs: [
      { indexed: true, name: "requestId", type: "uint256" },
      { indexed: true, name: "purchaser", type: "address" },
      { indexed: false, name: "acquisitionFee", type: "uint256" },
      { indexed: false, name: "totalWeight", type: "uint256" },
    ],
  },
] as const;

export const erc721Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getApproved",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "isApprovedForAll",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "operator", type: "address" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  {
    type: "function",
    name: "tokenURI",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "highestMintedTokenId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const fwaRewardsAbi = [
  { type: "function", name: "claimsEnabled", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "emissionConfigured", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "currentSeason", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "seasonalReserveRemaining", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "seasonalEmitted", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "seasonalBurned", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "seasonalDepositorEmitted", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "seasonalPurchaserEmitted", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "buybackDepositorRouted", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "buybackPurchaserRouted", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "effectiveSeasonQuoteX96", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "VALUE_CAP_BPS", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "EMISSION_DURATION", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "seasonBudget", stateMutability: "pure", inputs: [{ name: "season", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "settledHypeInEpoch", stateMutability: "view", inputs: [{ name: "epoch", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "userSettledHypeInEpoch", stateMutability: "view", inputs: [{ name: "epoch", type: "uint256" }, { name: "purchaser", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "epochFinalized", stateMutability: "view", inputs: [{ name: "epoch", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "emissionStart", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "depositorEmissionRemaining", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "tokenLiability", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "depositorRatePerSec",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "purchaserDailyPot",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "hotGap", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "coldGap", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "lastAcquisitionTs",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "currentEpoch", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  {
    type: "function",
    name: "tokenCredit",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenBuyAllowance",
    stateMutability: "view",
    inputs: [{ name: "purchaser", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pendingDepositorTokens",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pendingAcquisitionsInEpoch",
    stateMutability: "view",
    inputs: [{ name: "epoch", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "userAcquisitionsInEpoch",
    stateMutability: "view",
    inputs: [{ name: "epoch", type: "uint256" }, { name: "purchaser", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "purchaserClaimed",
    stateMutability: "view",
    inputs: [{ name: "epoch", type: "uint256" }, { name: "purchaser", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "purchaserEpochSwept",
    stateMutability: "view",
    inputs: [{ name: "epoch", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "purchaserEpochAmount",
    stateMutability: "view",
    inputs: [{ name: "epoch", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "acquisitionsInEpoch",
    stateMutability: "view",
    inputs: [{ name: "epoch", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "claimDepositorTokens",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingIds", type: "uint256[]" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "claimEpochTokens",
    stateMutability: "nonpayable",
    inputs: [{ name: "epochs", type: "uint256[]" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "withdrawTokens", stateMutability: "nonpayable", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "claimAccruedTokens",
    stateMutability: "nonpayable",
    inputs: [{ name: "minOut", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const splitterAbi = [
  { type: "function", name: "NFT_ADDRESS", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "SNAPSHOT_SUPPLY", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "MAX_TOKEN_ID", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "SWEEP_AVAILABLE_AT", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "claimsClosed", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "splitFrozen", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "nftShareBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint16" }] },
  { type: "function", name: "claimablePerToken", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "pending",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ name: "tokenIds", type: "uint256[]" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
] as const;

export const erc20Abi = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "externalBuysEnabled", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
] as const;

export const v3PoolAbi = [
  { type: "function", name: "token0", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "token1", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    type: "function",
    name: "slot0",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "sqrtPriceX96", type: "uint160" },
      { name: "tick", type: "int24" },
      { name: "observationIndex", type: "uint16" },
      { name: "observationCardinality", type: "uint16" },
      { name: "observationCardinalityNext", type: "uint16" },
      { name: "feeProtocol", type: "uint8" },
      { name: "unlocked", type: "bool" },
    ],
  },
] as const;

/** On-chain ListingStatus enum → domain status. */
export const LISTING_STATUS_BY_CODE = {
  0: undefined, // None
  1: "active",
  2: "allocated",
  3: "withdrawn",
  4: "settled",
  5: "staged",
} as const;
